version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "00:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: influxdb-client
    versions:
    - 1.15.0
